[package]
name = "backend"
version = "0.1.0"
edition = "2021"

[dependencies]
rocket = { version = "0.5.1", features = ["json"] }
serde = "1.0.136"
chrono = "0.4"
diesel = { version = "2.2.0", features = ["postgres"] }
dotenvy = "0.15"
